= Jeti Transmitter EX Telemetry C++ Library for Arduino =

Protocol decoder for Jeti EX data output a JETI transmitters (Dx14/Dx16/Dx24).
   For Arduino Leonardo/Pro Micro and Teensy 3.x. Experimental for ESP32

  Version history:

    0.90   11/22/2017  created (BETA)

    0.91   11/12/2017  - 8 bit UART mode added. Define TXJETIEX_ARDUINO_UART in .ino
                       - Enumeration of names and labels
    0.92   11/13/2017  - bug fix in debug output
                       - 8 bit UART mode bug fix and baud rate tuning.
    0.93   11/15/2017  first experimental shot for ESP32 support
    0.94   12/05/2017  examples added for ESP32 and Bluefruit LE UART friend
    0.95   12/20/2017  ESP32 BLE Locator application added with Android App
   
== License ==

 Copyright (C) 2017 by Bernd Wokoeck

  Permission is hereby granted, free of charge, to any person obtaining
  a copy of this software and associated documentation files (the "Software"),
  to deal in the Software without restriction, including without limitation
  the rights to use, copy, modify, merge, publish, distribute, sublicense,
  and/or sell copies of the Software, and to permit persons to whom the
  Software is furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
  IN THE SOFTWARE.
